# 2024.01.11 yaml fix
server:
  port: 8484

# ajpPort
tomcat:
  ajp:
    protocol: AJP/1.3
    enabled: true
    remoteauthentication: false
    port: 9091

# InternalResourceViewResolver
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  #    hiddenmethod:
  #      filter:
  #        enabled: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@//localhost:1521/xe
    username: acc78nexa2
    password: acc78nexa2
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        flushMode: COMMIT
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: seoulit50@gmail.com
    password: "!admin8282"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
        auth: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  redis:
    port: 6379
    host: localhost
  cache:
    type: redis
    redis:
      time-to-live: 600s
  profiles:
    active: prod



# mybatis
mybatis:
  mapper-locations: classpath:/sqlMapper/**/**/*.xml
  type-aliases-package: kr.co.seoulit.erp.account
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true

# logging
logging:
  level:
    org.hibernate: info
    com.azurealstn.codespringweb.mapper: debug
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true


#swagger
springdoc:
  api-docs:
    path: /api-docs      #api-docs url : localhost:8080/api-docs
    groups:
      enabled: true      #group 허용
  swagger-ui:
    path: /index.html           # Swagger UI 경로
    enabled: true
    groups-order: ASC      #group 정렬 오름차순
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    display-request-duration: true
    doc-expansion: none          #swagger tag 리스트 펼치기 (none : 모두 접기 / list : 파트별 펼치기(내용 감추기)/full : 모두 펼치기)
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true        #returnType ModelAndView도 Swagger에 노출
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
